### ISSUE TITLE
Gatling 3 - NoSuchMethodError io.gatling.core.Predef$.csv

### ISSUE THREAD

**Issue by narendra15** [gatling/gatling#3756]
I'm currently using Gatling 3.1.3 which is the latest version and I tried to update my performance tests to have the latest changes.  Did mvn clean install and the build is success.
When running the tests It gives error at the ".feed". Below is the error:

**Error:**
Exception in thread "main" java.lang.NoSuchMethodError: io.gatling.core.Predef$.csv(Ljava/lang/String;CLio/gatling/core/config/GatlingConfiguration;)Lio/gatling/core/feeder/SourceFeederBuilder;

Can you please help me fix the issue. 

**Below is the code:**
import scala.concurrent.duration._
import io.gatling.core.Predef._
import io.gatling.core.structure.ScenarioBuilder
import io.gatling.http.Predef._

  val rolesAccessKeySample: ScenarioBuilder = scenario("Access key authentication")
    .feed(csv("access-keys.csv"))
    .exec(localModeSupport)
    .repeat(Iterations) {
      exec(http("get roles")
        .get(resolveUrl("security", "roles", "NEP_IDENTITY_VIEWER")))
        .pause(1 second, 3 seconds)
    }

**Key Changes:**
Updated my pom to use 3.1.3 version for gatling-core, gatling-app and gatling-http. Also added async-http-client with version 2.10.0.

Thank you

**Comment by slandelle** [comment]
You must `clean` in order to properly recompile.

**Comment by narendra15** [comment]
Thanks for the quick reply. I did mvn clean and then a mvn clean install.
But still getting the error at .feed . Exception in thread "main" java.lang.NoSuchMethodError: io.gatling.core.Predef$.csv(Ljava/lang/String;CLio/gatling/core/config/GatlingConfiguration;)Lio/gatling/core/feeder/SourceFeederBuilder;

**Comment by slandelle** [comment]
Please provide a full maven project sample.

**Comment by narendra15** [comment]
Sure, here is my sample project.
[sample.zip](https://github.com/gatling/gatling/files/3333882/sample.zip)

**Comment by slandelle** [comment]
This is not a sample, this is a large internal project that seams to be generating Gatling code on the fly.
Please provide a simple sample.

**Comment by narendra15** [comment]
Yes its a large project, but just executing a simple simulation and it gives error at the 
.feed(csv("access-keys.csv")) with below error: 
Exception in thread "main" java.lang.NoSuchMethodError: io.gatling.core.Predef$.csv(Ljava/lang/String;CLio/gatling/core/config/GatlingConfiguration;)Lio/gatling/core/feeder/SourceFeederBuilder;

I knew it was some dependency error,  that is why I shared my whole maven project, so that you can help me fix that issue.

**Comment by slandelle** [comment]
I ran `mvn clean compile test-compile` and it compiled just fine.

**Comment by narendra15** [comment]
Thanks again. But as told before no compilation errors. It is when running the tests.

**Comment by slandelle** [comment]
You've built your own custom platform to generate Gatling tests. I have no idea how it works but the problem is on your side.

**Comment by narendra15** [comment]
:-), I got you. But the error is coming only after I upgraded from gatling version 2.3.0 to 3.1.3. So only reached here.

**Comment by slandelle** [comment]
Really, we from GatlingCorp can't help with an internal custom platform.
Moreover, there's a good chance the features it has are covered in FrontLine.

**Comment by chcyang** [comment]
i met a similar problem that caused by i got version conflict of gatling, i have both 3.0.3 and 3.1.2 in one project.
