### ISSUE TITLE
Gatling conflicts with Quicklens in Scala 3

### ISSUE THREAD

**Issue by Iltotore** [gatling/gatling#4576]
Gatling is built with Scala 2.13 and therefore uses `quicklens_2.13`. This is a concern in Scala 3 projects that depend on `quicklens_3` because these two artifacts are not compatible, resulting in runtime errors when choosing a dependency in favor of another:

```scala
...
[error]	 java.lang.NoSuchMethodError: 'void com.softwaremill.quicklens.package$PathModify.<init>(java.lang.Object, scala.Function2)'
[error] 	at io.gatling.http.request.builder.HttpRequestBuilder.check(HttpRequestBuilder.scala:84)
``` 

Here is the two different signatures of this method:
- [In Quicklens for Scala 3](https://github.com/softwaremill/quicklens/blob/d4c24cab20067b393985caf129c41c70f40a3640/quicklens/src/main/scala-3/com/softwaremill/quicklens/package.scala#L33)
- [In Quicklens for Scala 2.13](https://github.com/softwaremill/quicklens/blob/d4c24cab20067b393985caf129c41c70f40a3640/quicklens/src/main/scala-2.13%2B/com.softwaremill.quicklens/package.scala#L56)

A potential solution is to make Gatling cross compile in Scala 2.13 and 3 in order to use the Scala 3 Quicklens for `gatling-..._3` artifacts.

**Comment by slandelle** [comment]
I don't think cross compiling Gatling will ever happen.

IMHO, your problem is not specific to quicklens.

Your actual issue is probably that your Gatling tests import the classpath of your actual application, resulting both in versions clash and in pulling extra luggage in your Gatling Enterprise packages (how many times have I seen customers shipping Spring, Hibernate and Selenium, along with their sensitive code 🙄).

I think it's a good practice to isolate Gatling tests and the actual application classpaths.

**Comment by slandelle** [comment]
I'd argue that this problem is very specific to your project where your model depends on quicklens.

> In its current state, what prevents Gatling to be compiled against Scala 3 for _3 artifacts (while keeping 2.13.4 for _2.13 of course)?

Cost (don't see only the open-source part but the Enterprise one too) vs benefit.
Your organization is currently our only customer with an interest in Scala 3. Sad but true.

**Comment by slandelle** [comment]
Would forking quicklens into an internal package work? I'm not sure how Scala 2 macros work on Scala 3.

**Comment by Iltotore** [comment]
Scala 2 macros do not work on Scala 3 but Gatling is still usable with Scala 3 as long as we not use these 2.13.x macros.

**Comment by slandelle** [comment]
Are you sure?
We're not talking about compiling code with Scala 3 with Scala 2.13 macros.
We're talking about running with Scala 3 some code that was compiled with the Scala 2.13 compiler using some Scala 2.13 macros.

**Comment by Iltotore** [comment]
Indeed, running Scala 3 code with some code compiled in 2.13 with macros works. We managed to still run Gatling on our S3 codebase by using the `_2.13` artifact at runtime althrough this feel like a dirty hack.

**Comment by slandelle** [comment]
I think we're going to ship a translated version of quicklens (meaning a different package) in Gatling 3.12.
Just not sure if we're going to do this with a simple shadowing, or if we're going to fork the sources.

**Comment by slandelle** [comment]
It turned out that there's no easy way to shade macros because packages are also present in quasiquotes Strings.
