### ISSUE TITLE
Migrating Gatling java from v3.9.5 to v3.10.5  results in a compilation error

### ISSUE THREAD

**Issue by tinomthomas** [gatling/gatling#4552]
## Problem
Migrating Gatling java from v3.9.5 to v3.10.5 results in a compilation error.

## Classes and methods resulted in compilation error
1. `io.gatling.commons.stats.assertion.AssertionPath#printable`
2. `io.gatling.commons.stats.assertion.Target#printable`
3. `io.gatling.commons.stats.assertion.Condition#printable`
4. `io.gatling.commons.stats.assertion.Condition#values`

## Hint
This is happening because of the below dependency change:
`gatling-commons-shared` -> `gatling-shared-model`

**Comment by slandelle** [comment]
Please explain what you’re doing and why you feel this is a bug.

Reminder:
• you’re only supposed to explicitly pull the highcharts module, as demoed in our documentation and samples. The other ones must be pulled transitively.
• you’re supposed to use wildcards imports like documented.

Any other configuration is your decision and hence your responsibility.

**Comment by tinomthomas** [comment]
@slandelle Apologies for not providing more context to the problem. Let me add more context:

We are using the below code to log the human-readable assertion text with `printable()` and `values()` methods, mentioned in my issue description, during the performance test run:

```java
public static String toString(Assertion assertion) {
  var s = assertion.asScala();
  return s.path().printable() + ": "
    + s.target().printable() + " "
    + s.condition().printable() + " "
    + s.condition().values().mkString(", ");
}
```
The above code worked perfectly with version 3.9.5, but when I tried to migrate to version 3.10.5, the compiler could not find the `printable()` and `values()` methods.

When I analyzed the dependency tree, I found out that the issue happened because of the dependency change in version 3.10.5

Regarding your comments, I am adding my response inline: 
-  "you’re only supposed to explicitly pull the highcharts module, as demoed in our documentation and samples. The other ones must be pulled transitively."
    _**Yes this is what we are doing**_
- "you’re supposed to use wildcards imports like documented."
  _**The issue persists for both wildcard import and specific import**_

**Comment by tinomthomas** [comment]
@slandelle I see. Thanks for the clarification. 

In that case, would you suggest an alternative for me to print the human-readable assertion text?

**Comment by slandelle** [comment]
Sorry but this is not a feature we provide.
The assertions are meant to be generated internally by Gatling and printed in one of the official Gatling outputs (console, HTML reports, Gatling Enterprise).
I recommend that you stick to these.
