### ISSUE TITLE
gatling-recorder does not compile using JDK 1.6

### ISSUE THREAD

**Issue by peterlynch** [gatling/gatling#923]
Building master branch with Maven 3.0.4 and JDK 1.6:

```
INFO] --- scala-maven-plugin:3.1.2:compile (default) @ gatling-recorder ---
[INFO] /Users/plynch/dev/gatling/gatling-recorder/src/main/scala:-1: info: compiling
[INFO] Compiling 36 source files to /Users/plynch/dev/gatling/gatling-recorder/target/classes at 1358516865405
[ERROR] /Users/plynch/dev/gatling/gatling-recorder/src/main/scala/com/excilys/ebi/gatling/recorder/ui/frame/ConfigurationFrame.scala:54: error: javax.swing.JComboBox does not take type parameters
[ERROR]     val cbFilterStrategies = new JComboBox[FilterStrategy.Value]
[ERROR]                                      ^
[ERROR] /Users/plynch/dev/gatling/gatling-recorder/src/main/scala/com/excilys/ebi/gatling/recorder/ui/frame/ConfigurationFrame.scala:60: error: javax.swing.JComboBox does not take type parameters
[ERROR]     val cbOutputEncoding = new JComboBox[Charset]
[ERROR]                                    ^
[ERROR] /Users/plynch/dev/gatling/gatling-recorder/src/main/scala/com/excilys/ebi/gatling/recorder/ui/frame/RunningFrame.scala:42: error: javax.swing.DefaultListModel does not take type parameters
[ERROR]     private val eventsInfo = new DefaultListModel[EventInfo]
[ERROR]                                      ^
[ERROR] /Users/plynch/dev/gatling/gatling-recorder/src/main/scala/com/excilys/ebi/gatling/recorder/ui/frame/RunningFrame.scala:43: error: javax.swing.DefaultListModel does not take type parameters
[ERROR]     private val hostsCertificate = new DefaultListModel[String]
[ERROR]                                            ^
[ERROR] four errors found
```

Using Java 7 does work. Not sure this was intentional or not so thought I would mention it.

If its intentional, suggest adding an maven enforcer rule that makes sure JDK being used is 1.7 or greater.
