### ISSUE TITLE
Possible bug after update to 3.11.X

### ISSUE THREAD

**Issue by matzalew** [gatling/gatling#4570]
Hello.
Updated today 

- gatling-charts-highcharts to 3.11.3
- gatling-maven-plugin to       4.9.1

I tried running the REST tests that I had - they worked fine.
But with the JMS test that we have, there's some problem - the tests fail because the files created by 

                        .bodyPart(ElFileBodyPart("file", session -> "some_path" + session.get("randomId") + session.get("n") + ".csv")
                                .contentType(ContentType.APPLICATION_MS_EXCEL.getValue())
                                .fileName(session -> "Test" + session.get("randomId") + session.get("n") +".csv"))

sometimes the tests run OK but with failed result *with logs like:
POST importing data from file: Resource some_path-20181977530.csv not found , 

And sometimes the tests does not start with:

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.gatling.plugin.util.ForkMain.runMain(ForkMain.java:67)
	at io.gatling.plugin.util.ForkMain.main(ForkMain.java:35)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.gatling.app.SimulationClass$Java.params(SimulationClass.scala:47)
	at io.gatling.app.Runner.load(Runner.scala:74)
	at io.gatling.app.Runner.run(Runner.scala:59)
	at io.gatling.app.Gatling$.start(Gatling.scala:86)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:48)
	at io.gatling.app.Gatling$.main(Gatling.scala:42)
	at io.gatling.app.Gatling.main(Gatling.scala)
	... 6 more
Caused by: java.lang.NoSuchMethodError: 'io.gatling.javaapi.http.HttpRequestActionBuilder io.gatling.javaapi.http.HttpRequestActionBuilder.bodyPart(io.gatling.javaapi.http.BodyPart)'

Anyone had similar issue, and could help? I got thru the migration guide from the 3.10.5 to 3.11.3 and from 4.8.2 to 4.9.1. There was no problem.

Any help would be great :)

**Comment by slandelle** [comment]
> Caused by: java.lang.NoSuchMethodError: 'io.gatling.javaapi.http.HttpRequestActionBuilder io.gatling.javaapi.http.HttpRequestActionBuilder.bodyPart(io.gatling.javaapi.http.BodyPart)

The only way to get this is to compile with Gatling 3.10 and then try to run the compiled classes with Gatling 3.11.
Not a Gatling bug.
